
pipeline {

    parameters {
        string(name: 'environment', defaultValue: 'terraformenv', description: 'Workspace/environment file to use for deployment')
        booleanParam(name: 'autoApprove', defaultValue: true, description: 'Automatically run apply after generating plan?')

    }


     environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

   agent  any
        options {
                timestamps ()
                ansiColor('xterm')
            }
        tools{terraform 'Terraform'}
    stages {
        
        stage('Checkout') {
            steps {
                 script{
                        dir("terraformDir")
                        {
                            git (
                                branch: 'main',
                                url: 'https://github.com/cphussain/Jinkins-Terraform.git'
                            )
                        }
                    }
                }
            }

        stage('Plan') {
            steps {
               script{
                        dir("aws/CreateEC2")
                        {
                            bat 'terraform --version'
                            bat 'cd terraformDir/aws/CreateEC2'
                            bat 'terraform init -input=false'
                            bat 'terraform workspace new ${environment}'
                            bat 'terraform workspace select ${environment}'
                            bat "terraform plan -input=false -out tfplan "
                            bat 'terraform show -no-color tfplan > tfplan.txt'
                        }
               }
            }
        }
        stage('Approval') {
           when {
               not {
                   equals expected: true, actual: params.autoApprove
               }
           }

           steps {
               script {
                    def plan = readFile 'aws/CreateEC2/tfplan.txt'
                    input message: "Do you want to apply the plan?",
                    parameters: [text(name: 'Plan', description: 'Please review the plan', defaultValue: plan)]
               }
           }
       }

        stage('Apply') {
            steps {
                sh "pwd;cd aws/CreateEC2 ; terraform apply -input=false tfplan"
            }
        }
    }

  }
