
pipeline {
     environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')

    }

   agent  any
        options {
                timestamps ()
                ansiColor('xterm')
            }
        tools{
            terraform 'Terraform'
            }
            
    stages {
        
        stage('Checkout') {
            steps {
                 script{
                        dir("terraformDir")
                        {
                            git (
                                branch: 'main',
                                url: 'https://github.com/cphussain/Jinkins-Terraform.git'
                                
                            )
                        }
                    }
                }
            }


        stage('Plan') {
            steps {
               script{
                        dir("aws/CreateEC2")
                        {
                            
                            bat 'terraform --version'
                           
                            bat 'terraform init -input=false'
                            bat 'terraform workspace delete terraformenv -force'
                            bat 'terraform workspace new terraformenv'
                            bat 'terraform workspace select terraformenv'
                            bat "terraform plan -input=false -out tfplan "
                            bat 'terraform show -no-color tfplan > tfplan.txt'
                        }
               }
            }
        }
        

        stage('Apply') {
            steps { script{
                        dir("aws/CreateEC2")
                        {
                bat "terraform apply -input=false tfplan"
                        }}
            }
        }
    }

  }
